# Generated by Django 5.2 on 2025-04-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='pickup_location',
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_building',
            field=models.CharField(default='Dorm', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_speed',
            field=models.CharField(default='Standard', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='fragile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='package_type',
            field=models.CharField(default='Box', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='pickup_building',
            field=models.CharField(default='Gate', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='pickup_instructions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='weight',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
    ]
