# Generated by Django 5.2 on 2025-04-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_deliveryorder_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='qr_code_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
