# Generated by Django 5.2 on 2025-04-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deliveryorder_qr_code_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='qr_code_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
