# Generated by Django 5.2 on 2025-04-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_deliveryorder_qr_code_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='qr_code_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
