# Generated by Django 5.2 on 2025-05-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_deliveryorder_qr_code_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_dispatcher",
            field=models.BooleanField(default=False),
        ),
    ]
