# Generated by Django 5.2 on 2025-05-22 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="content",
            new_name="message",
        ),
    ]
