# Generated by Django 5.2 on 2025-07-30 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_content_message_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='current_order',
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_room',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='qr_payload_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='qr_signature',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='robot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.robot'),
        ),
        migrations.AddField(
            model_name='robot',
            name='status',
            field=models.CharField(choices=[('IDLE', '空闲'), ('LOADING', '装货中'), ('DELIVERING', '配送中'), ('MAINTENANCE', '维护中')], default='IDLE', max_length=20),
        ),
    ]
