# Generated by Django 5.2 on 2025-07-31 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_robot_current_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryorder",
            name="qr_is_valid",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="deliveryorder",
            name="qr_scanned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="robot",
            name="battery_level",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="robot",
            name="current_delivery_location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="robot",
            name="current_location",
            field=models.CharField(default="Warehouse", max_length=100),
        ),
        migrations.AddField(
            model_name="robot",
            name="delivery_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="robot",
            name="door_status",
            field=models.CharField(
                choices=[("OPEN", "开门"), ("CLOSED", "关门")],
                default="CLOSED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="robot",
            name="last_status_update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="robot",
            name="qr_wait_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "待分配"),
                    ("ASSIGNED", "已装入机器人"),
                    ("DELIVERING", "配送中"),
                    ("DELIVERED", "已送达"),
                    ("PICKED_UP", "已取出"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="robot",
            name="status",
            field=models.CharField(
                choices=[
                    ("IDLE", "空闲"),
                    ("LOADING", "装货中"),
                    ("DELIVERING", "配送中"),
                    ("MAINTENANCE", "维护中"),
                    ("RETURNING", "返航中"),
                ],
                default="IDLE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "信息"),
                            ("WARNING", "警告"),
                            ("ERROR", "错误"),
                            ("SUCCESS", "成功"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("ROBOT_CONTROL", "机器人控制"),
                            ("ORDER_STATUS", "订单状态"),
                            ("QR_SCAN", "二维码扫描"),
                            ("SYSTEM", "系统"),
                            ("DELIVERY", "配送"),
                        ],
                        default="SYSTEM",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.deliveryorder",
                    ),
                ),
                (
                    "robot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.robot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="core_system_timesta_7e67e4_idx"
                    ),
                    models.Index(fields=["level"], name="core_system_level_bf5286_idx"),
                    models.Index(
                        fields=["log_type"], name="core_system_log_typ_61d765_idx"
                    ),
                ],
            },
        ),
    ]
