# Generated by Django 5.2 on 2025-07-31 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_deliveryorder_qr_is_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('PENDING', '待分配'), ('ASSIGNED', '已装入机器人'), ('DELIVERING', '配送中'), ('DELIVERED', '已送达'), ('PICKED_UP', '已取出'), ('CANCELLED', '已作废')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='RobotCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(choices=[('open_door', '开门'), ('close_door', '关门'), ('start_delivery', '开始配送'), ('stop_robot', '停止机器人'), ('arrived_at_destination', '到达目的地'), ('auto_return', '自动返航')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', '待执行'), ('EXECUTING', '执行中'), ('COMPLETED', '已完成'), ('FAILED', '执行失败'), ('CANCELLED', '已取消')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='core.robot')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '机器人指令',
                'verbose_name_plural': '机器人指令',
                'ordering': ['-sent_at'],
            },
        ),
    ]
