# Generated by Django 5.2 on 2025-08-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_deliveryorder_status_robotcommand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='log_type',
            field=models.CharField(choices=[('ROBOT_CONTROL', '机器人控制'), ('ORDER_STATUS', '订单状态'), ('QR_SCAN', '二维码扫描'), ('SYSTEM', '系统'), ('DELIVERY', '配送'), ('NETWORK_REQUEST', '网络请求'), ('NETWORK_RESPONSE', '网络响应'), ('NETWORK_ERROR', '网络错误'), ('WEBSOCKET_CONNECTION', 'WebSocket连接')], default='SYSTEM', max_length=20),
        ),
    ]
