# Generated by Django 5.2 on 2025-08-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_systemlog_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotcommand',
            name='command',
            field=models.CharField(choices=[('open_door', '开门'), ('close_door', '关门'), ('start_delivery', '开始配送'), ('stop_robot', '停止机器人'), ('arrived_at_destination', '到达目的地'), ('auto_return', '自动返航'), ('emergency_open_door', '紧急开门')], max_length=50),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='log_type',
            field=models.CharField(choices=[('ROBOT_CONTROL', '机器人控制'), ('ORDER_STATUS', '订单状态'), ('QR_SCAN', '二维码扫描'), ('SYSTEM', '系统'), ('DELIVERY', '配送'), ('NETWORK_REQUEST', '网络请求'), ('NETWORK_RESPONSE', '网络响应'), ('NETWORK_ERROR', '网络错误')], default='SYSTEM', max_length=50),
        ),
    ]
